version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  node-app:
    build: .
    container_name: node-app
    ports:
      - "8081:8081"

